#!/usr/bin/python3
"""
a file that contains the class definition of
a State and an instance Base = declarative_base():
"""

from sqlalchemy import create_engine
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class State(Base):
    """
    inherits from class Base
    links to MySQL table - states
    class attribute - id represents the colunm of autogenerated
    unique integer, can't be null and is a primary key
    class attribute - name that rep a column of a string with maximum
    128 characters and cna't be null
    """
    __tablename__ = "states"

    id = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    name = Column(String(128), nullable=False)
